---
- name: Install 1Password
  tags:
    - onepassword
  block:
    - name: Add 1Password repository key
      ansible.builtin.rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Add 1Password repository
      ansible.builtin.yum_repository:
        name: onepassword
        description: 1Password Repository
        baseurl: https://downloads.1password.com/linux/rpm/stable/x86_64/
        enabled: true
        gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Install 1Password package
      ansible.builtin.dnf:
        name: 1password
        state: present
