---
- name: Install Fish Shell with plugins
  tags:
    - fish
  block:
    - name: Install fish shell
      ansible.builtin.dnf:
        name: fish
        state: present

    - name: Create fish config directory for user
      ansible.builtin.file:
        path: /home/{{ username }}/.config/fish
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Check if fisher is installed
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher_loader.fish
      register: fisher_installed

    - name: Install Fisher (plugin manager) - Try curl method
      ansible.builtin.shell:  # noqa: command-instead-of-shell risky-shell-pipe command-instead-of-module[curl]
        cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/boot.fish | fish && fisher update
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: fisher_install
      changed_when: "'fisher' in fisher_install.stderr or 'fisher' in fisher_install.stdout"
      failed_when: false
      when: not fisher_installed.stat.exists

    - name: Install Fisher (plugin manager) - Fallback git method
      ansible.builtin.git:  # noqa: latest
        repo: https://github.com/jorgebucaran/fisher.git
        dest: /tmp/fisher
        depth: 1
        version: main
      become: true
      become_user: "{{ username }}"
      register: fisher_git_clone
      when: not fisher_installed.stat.exists and fisher_install.rc | default(1) != 0

    - name: Run Fisher installer script
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: fish -c "source /tmp/fisher/boot.fish && fisher update"
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: fisher_script_install
      changed_when: "'fisher' in fisher_script_install.stderr or 'fisher' in fisher_script_install.stdout"
      when: not fisher_installed.stat.exists and fisher_git_clone is changed

    - name: Wait for fisher to be available
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher_loader.fish
      register: fisher_binary
      until: fisher_binary.stat.exists
      retries: 3
      delay: 2
      when: not fisher_installed.stat.exists

    - name: Install nvm plugin with fisher
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: /home/{{ username }}/.local/share/fish/vendor_functions.d/fisher install edc/bass
      become: true
      become_user: "{{ username }}"
      register: nvm_plugin_install
      changed_when: "'installed' in nvm_plugin_install.stdout"
      failed_when: false

    - name: Install tide prompt plugin with fisher
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: /home/{{ username }}/.local/share/fish/vendor_functions.d/fisher install IlanCosman/tide
      become: true
      become_user: "{{ username }}"
      register: tide_plugin_install
      changed_when: "'installed' in tide_plugin_install.stdout"
      failed_when: false

    - name: Configure fish config.fish with Fisher plugins
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "{{ item }}"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      loop:
        - "# Tide Prompt Configuration"
        - "set -g tide_prompt_icon_success '✔'"
        - "set -g tide_prompt_icon_failure '✘'"

    - name: Set fish as default shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Display fish shell installation status
      ansible.builtin.debug:
        msg: |
          Fish shell installed successfully with:
          - Fisher plugin manager
          - Bass (bash compatibility)
          - Tide prompt

          To install additional plugins with fisher, run: fisher install <github-user>/<plugin-name>
          Current shell: /usr/bin/fish
