---
- name: Install Fish Shell with plugins
  tags:
    - fish
  block:
    - name: Install fish shell
      ansible.builtin.dnf:
        name: fish
        state: present

    - name: Create fish config directory for user
      ansible.builtin.file:
        path: /home/{{ username }}/.config/fish
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Check if fisher is installed
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher_loader.fish
      register: fisher_installed

    - name: Install Fisher (plugin manager)
      ansible.builtin.git:  # noqa: latest
        repo: https://github.com/jorgebucaran/fisher.git
        dest: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher
        depth: 1
        version: main
      become: true
      become_user: "{{ username }}"
      register: fisher_git_clone
      when: not fisher_installed.stat.exists

    - name: Create fisher loader in vendor_conf.d
      ansible.builtin.file:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
      become: true
      become_user: "{{ username }}"
      when: not fisher_installed.stat.exists and fisher_git_clone is changed

    - name: Create fisher loader script
      ansible.builtin.copy:
        content: |
          # fisher loader
          set -l fisher_path /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher
          set -l fisher_bin_path $fisher_path/bin/fisher.fish
          if test -f $fisher_bin_path
            source $fisher_bin_path
          end
        dest: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher_loader.fish
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      become: true
      become_user: "{{ username }}"
      when: not fisher_installed.stat.exists and fisher_git_clone is changed

    - name: Wait for fisher to be available
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher_loader.fish
      register: fisher_binary
      until: fisher_binary.stat.exists
      retries: 3
      delay: 2
      when: not fisher_installed.stat.exists

    - name: Install bass plugin with fisher
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: fish -c "/home/{{ username }}/.local/share/fish/vendor_conf.d/fisher/bin/fisher.fish install edc/bass"
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: bass_plugin_install
      changed_when: "'installed' in bass_plugin_install.stdout"
      failed_when: false
      when: fisher_git_clone is changed or fisher_installed.stat.exists

    - name: Install tide prompt plugin with fisher
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: fish -c "/home/{{ username }}/.local/share/fish/vendor_conf.d/fisher/bin/fisher.fish install IlanCosman/tide"
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: tide_plugin_install
      changed_when: "'installed' in tide_plugin_install.stdout"
      failed_when: false
      when: fisher_git_clone is changed or fisher_installed.stat.exists

    - name: Configure fish config.fish with Fisher plugins
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "{{ item }}"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      loop:
        - "# Tide Prompt Configuration"
        - "set -g tide_prompt_icon_success '✔'"
        - "set -g tide_prompt_icon_failure '✘'"

    - name: Set fish as default shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Display fish shell installation status
      ansible.builtin.debug:
        msg: |
          Fish shell installed successfully with:
          - Fisher plugin manager
          - Bass (bash compatibility)
          - Tide prompt

          To install additional plugins with fisher, run: fisher install <github-user>/<plugin-name>
          Current shell: /usr/bin/fish
