---
- name: Install Fish Shell with plugins
  tags:
    - fish
  block:
    - name: Install fish shell
      ansible.builtin.dnf:
        name: fish
        state: present

    - name: Create fish config directory for user
      ansible.builtin.file:
        path: /home/{{ username }}/.config/fish
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Check if fisher is installed
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher/functions/fisher.fish
      register: fisher_installed

    - name: Install Fisher (plugin manager)
      ansible.builtin.shell:  # noqa: command-instead-of-shell risky-shell-pipe
        cmd: |
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
          if [ -f /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher/functions/fisher.fish ]; then
            echo "installed"
          else
            echo "failed"
          fi
      become: true
      become_user: "{{ username }}"
      register: fisher_install
      changed_when: "'installed' in fisher_install.stdout"
      failed_when: "'failed' in fisher_install.stdout"
      when: not fisher_installed.stat.exists

    - name: Wait for fisher to be available
      ansible.builtin.stat:
        path: /home/{{ username }}/.local/share/fish/vendor_conf.d/fisher/functions/fisher.fish
      register: fisher_binary
      until: fisher_binary.stat.exists
      retries: 3
      delay: 2

    - name: Ensure Fisher functions are in fish_function_path
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "set -gp fish_function_path $HOME/.local/share/fish/vendor_conf.d/fisher/functions"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
        insertbefore: "^# Tide"
      become: true
      become_user: "{{ username }}"

    - name: Install fisher plugins
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: fish -c "fisher install {{ item }}"
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: fisher_plugin_install
      changed_when: "'installed' in fisher_plugin_install.stdout"
      failed_when: false
      loop:
        - "edc/bass"
        - "IlanCosman/tide"
        - "jorgebucaran/nvm.fish"
        - "reitzig/sdkman-for-fish"
      when: fisher_binary.stat.exists

    - name: Install latest Node.js LTS version with nvm
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: fish -c "nvm install lts"
        executable: /usr/bin/fish
      become: true
      become_user: "{{ username }}"
      register: nvm_lts_install
      changed_when: "'Now using Node' in nvm_lts_install.stdout or 'Downloading' in nvm_lts_install.stdout"
      failed_when: false
      when: fisher_binary.stat.exists

    - name: Set latest Node.js LTS as default with nvm
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "set -Ux nvm_default_version lts"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      become: true
      become_user: "{{ username }}"

    - name: Configure fish config.fish with Fisher plugins
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "{{ item }}"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      loop:
        - "# Tide Prompt Configuration"
        - "set -g tide_prompt_icon_success '✔'"
        - "set -g tide_prompt_icon_failure '✘'"


    - name: Add cargo bin directory to PATH in fish config
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "fish_add_path $HOME/.cargo/bin"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      become: true
      become_user: "{{ username }}"

    - name: Add aliases to fish config
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.config/fish/config.fish
        line: "{{ item }}"
        state: present
        create: true
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      loop:
        - "# LS Aliases"
        - "alias ls='lsd'"
        - "alias l='ls -lha'"
        - "alias la='ls -lhA'"
        - "alias ll='ls -lAFh'"
        - "alias lla='lsd -la'"
        - "alias lsa='ls -lha'"
        - "alias lt='lsd --tree'"
        - ""
        - "# General Aliases"
        - "alias c=clear"
        - ""
        - "# Build Aliases"
        - "alias mcb='mvn clean build'"
        - "alias gcb='./gradlew clean build'"
        - "alias m='make'"
        - ""
        - "# System Aliases"
        - "alias tg='topgrade'"
        - "alias dcu='docker-compose up'"
        - ""
        - "# Git Aliases"
        - "alias gc='git commit'"
        - "alias gs='git status'"
        - "alias gp='git push'"
        - "alias gl='git pull'"
        - "alias gco='git checkout'"
        - "alias gd='git diff'"
        - "alias gb='git branch'"
        - "alias ga='git add'"
        - "alias glo='git log --oneline --decorate --color'"
        - ""
        - "# NPM Aliases"
        - "alias ni='npm install'"
        - "alias nid='npm install --save-dev'"
        - "alias nig='npm install -g'"
        - "alias nr='npm run'"
        - "alias ns='npm start'"
        - "alias nt='npm test'"
        - "alias nb='npm run build'"
        - "alias spot='./gradlew spotlessApply'"
        - ""
        - "# Utility Aliases"
        - "alias lad=lazydocker"
      become: true
      become_user: "{{ username }}"

    - name: Set fish as default shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Display fish shell installation status
      ansible.builtin.debug:
        msg: |
          Fish shell installed successfully with:
          - Fisher plugin manager
          - Bass (bash compatibility)
          - Tide prompt
          - NVM.fish (pure Fish Node Version Manager)
          - SDKMan for Fish (SDK Manager wrapper)

          Installed fisher plugins:
          - edc/bass
          - IlanCosman/tide
          - jorgebucaran/nvm.fish
          - reitzig/sdkman-for-fish

          To install additional plugins with fisher, run: fisher install <github-user>/<plugin-name>
          Current shell: /usr/bin/fish
