---
# Ansible collection requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.general
    version: ">=5.0.0"
