---
- name: Install Visual Studio Code
  tags:
    - vscode
  block:
    - name: Add Visual Studio Code repository key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code Repository
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Install Visual Studio Code package
      ansible.builtin.dnf:
        name: code
        state: present
