---
- name: Configure Git
  tags:
    - git
  block:
    - name: Ensure git is installed
      ansible.builtin.dnf:
        name: git
        state: present

    - name: Deploy .gitconfig file
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "{{ user_home }}/.gitconfig"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      notify: Git config deployed

    - name: Verify git configuration
      ansible.builtin.command:  # noqa: command-instead-of-module
        cmd: git config user.name
      register: git_config_check
      changed_when: false
      become_user: "{{ username }}"
      become: true
