---
- name: Install OpenJDK 25 Development
  tags:
    - openjdk-25
  block:
    - name: Install OpenJDK 25 and development tools
      ansible.builtin.dnf:
        name:
          - java-25-openjdk
          - java-25-openjdk-devel
          - java-25-openjdk-javadoc
        state: present

    - name: Find OpenJDK 25 installation path
      ansible.builtin.find:
        paths: /usr/lib/jvm
        patterns: 'java-25-openjdk*'
        file_type: directory
      register: java_25_paths

    - name: Set Java 25 environment variables
      ansible.builtin.lineinfile:
        path: /etc/profile.d/java25.sh
        line: "{{ item }}"
        state: present
        create: true
        owner: root
        group: root
        mode: '0644'
      loop:
        - "export JAVA_HOME=/usr/lib/jvm/java-25-openjdk"
        - "export PATH=$JAVA_HOME/bin:$PATH"

    - name: Check current default Java
      ansible.builtin.command:
        cmd: /usr/bin/java -version
      register: java_check
      changed_when: false
      ignore_errors: true

    - name: Set Java 25 as default Java with high priority
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: |
          alternatives --install /usr/bin/java java /usr/lib/jvm/java-25-openjdk/bin/java 200
          alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-25-openjdk/bin/javac 200
          alternatives --install /usr/bin/jar jar /usr/lib/jvm/java-25-openjdk/bin/jar 200
          alternatives --install /usr/bin/jarsigner jarsigner /usr/lib/jvm/java-25-openjdk/bin/jarsigner 200
          alternatives --set java /usr/lib/jvm/java-25-openjdk/bin/java
          alternatives --set javac /usr/lib/jvm/java-25-openjdk/bin/javac
      when: '"java-25" not in java_check.stderr'
      register: java_alternatives
      changed_when: java_alternatives.rc == 0

    - name: Verify OpenJDK 25 is default
      ansible.builtin.command:
        cmd: java -version
      register: java_version
      changed_when: false
