---
- name: Install Google Chrome Browser from Flathub
  tags:
    - chrome
  block:
    - name: Install chrome flatpak
      ansible.builtin.command:  # noqa: command-instead-of-module
        cmd: flatpak install --noninteractive flathub com.google.Chrome
      register: chrome_install
      changed_when: "'already installed' not in chrome_install.stderr"
      failed_when:
        - chrome_install.rc != 0
        - "'already installed' not in chrome_install.stderr"

    - name: Verify chrome installation
      ansible.builtin.command:  # noqa: command-instead-of-module
        cmd: flatpak list --app
      register: flatpak_list
      changed_when: false

    - name: Display chrome installation status
      ansible.builtin.debug:
        msg: "Google Chrome Browser has been installed from Flathub"
      notify: Chrome installed
