---
- name: Install OnlyOffice
  tags:
    - onlyoffice
  block:
    - name: Install onlyoffice from flathub
      ansible.builtin.command:  # noqa: command-instead-of-module
        cmd: flatpak install -y flathub org.onlyoffice.desktopeditors
      register: onlyoffice_install
      changed_when: "'already installed' not in onlyoffice_install.stderr and 'is already installed' not in onlyoffice_install.stderr"
      failed_when:
        - onlyoffice_install.rc != 0
        - "'already installed' not in onlyoffice_install.stderr"
        - "'is already installed' not in onlyoffice_install.stderr"
