---
- name: Provision Fedora 42 KDE Machine
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../.vars.yml"

  roles:
    - role: base
      tags:
        - base

    - role: clitools
      tags:
        - clitools

    - role: fonts
      tags:
        - fonts

    - role: hostname
      tags:
        - hostname

    - role: git
      tags:
        - git

    - role: docker
      tags:
        - docker

    - role: flatpak
      tags:
        - flatpak

    - role: bitwarden
      tags:
        - bitwarden

    - role: brave
      tags:
        - brave

    - role: chrome
      tags:
        - chrome

    - role: chromium
      tags:
        - chromium
