---
- name: Provision Fedora 42 KDE Machine
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/../.vars.yml"

  roles:
    - role: base
      tags:
        - base

    - role: git
      tags:
        - git
